### ISSUE TITLE
[Mesa redonda] QA-Empleo

### ISSUE THREAD

**Issue by RafaelAybar** [HacktoberfestES/hacktoberfestES2021-web#15]
### Nombre

QA-Empleo

### Fecha y hora

Finales de Septiembre

### Enlace

https://github.com/RafaelAybar/qa-empleo

### Descripción corta

En el hacktoberfest pasado vi la oportunidad de poder desarrollar QA-Empleo, un software que permite poder determinar si una oferta de empleo es buena o no, del modo más objetivamente posible.
Es decir, que ayude en la toma de decisiones de una manera fría y objetiva.

**Comment by dukebody** [comment]
Hola @RafaelAybar ! QA Empleo lo propones como proyecto, no como actividad, ¿no? Porque has utilizado la plantilla de actividad.

**Comment by RafaelAybar** [comment]
En realidad a parte de presentar el proyecto, me gustaría debatir qué funcionalidades le puede venir bien al proyecto

**Comment by RafaelAybar** [comment]
Añadí el topic

**Comment by carmeco** [comment]
Hola @RafaelAybar !

Acabo de añadir el proyecto a la web. Me falta algo de información:
 - Logo: de momento he puesto el del año pasado, pero si quieres lo cambiamos.
 - Tecnologías: he puesto Python, hay que añadir alguna más?
 - Comunidad: no he puesto nada, quieres añadir alguna?
