### ISSUE TITLE
[PROYECTO] Damegender - python

### ISSUE THREAD

**Issue by davidam** [HacktoberfestES/hacktoberfestES2021-web#16]
### Nombre

David

### Enlace a Github

https://github.com/davidam/damegender

### Tecnologías empleadas

Python
Bash

### Descripción corta

Es una herramienta de detección de género a partir del nombre. Te animo a que trates de utilizarla y si ves bugs o se te ocurren nuevas features, o no entiendes cómo se hace algo lo comentes trataré de explicar cómo hacerlo.

### Prepara tu proyecto para el HacktoberfestES

- [X] El proyecto está marcado con la etiqueta `hacktoberfest`.
- [X] El proyecto tiene un README indicando cómo configurarlo para desarrollar en él.
- [ ] El proyecto tiene creadas issues con información clara sobre las mejoras a implementar.

**Comment by dukebody** [comment]
¡Hola @davidam ! Gracias por sugerir tu proyecto.

Para que la gente pueda trabajar en él sería mejor que creases issues en el mismo describiendo posibles tareas. Si no, en general la gente no sabe qué hacer ya que no conoce el proyecto. ¿Podrías hacerlo?

También tendrías que aplicarle el topic `hacktoberfest` a tu repo.

¿Tienes alguna idea de logo?

**Comment by davidam** [comment]
He subido un par de issues a ver qué te parece. No quiero apabullar a
la gente con un montón de cosas que tengo en la cabeza. He tratado de
escoger un par de cuestiones que puedan animar porque si se sabe un
poquillo no se tarda mucho y si no es que no se sabía y se podría
enseñar incluso.

He puesto el topic hacktoberfest.

Tengo algún logo, pero prefiero continuar de manera que cambie la
imagen cada vez que se cargue la web ¿Es muy importante tener logo?

Saludos.

El 19/9/21, Israel Saeta Pérez ***@***.***> escribió:
> ¡Hola @davidam ! Gracias por sugerir tu proyecto.

>

> Para que la gente pueda trabajar en él sería mejor que creases issues en el
> mismo describiendo posibles tareas. Si no, en general la gente no sabe qué
> hacer ya que no conoce el proyecto. ¿Podrías hacerlo?

>

> También tendrías que aplicarle el topic `hacktoberfest` a tu repo.

>

> ¿Tienes alguna idea de logo?

>

> --

> You are receiving this because you were mentioned.

> Reply to this email directly or view it on GitHub:

> https://github.com/HacktoberfestES/hacktoberfestES2021-web/issues/16#issuecomment-922495078


-- 
David Arroyo Menéndez
http://www.davidam.com

**Comment by dukebody** [comment]
Hola. Mirando las issues, las veo un poco abstractas y sin más definición puede que le cueste a la gente ponerse a hacerlas. Así que yo te recomiendo que o bien las expliques un poco más directamente en la issue (preferible), o bien agendes alguna sesión de trabajo en la que puedas explicar cómo va el tema a la gente interesada.

Respecto al logo, es por no romper el diseño de https://hacktoberfestes.dev/, ya que todos los proyectos tienen logo y si no quedaría algo raro uno sin logo. Si no se te ocurre ninguno nos inventamos nosotros uno que pegue.

Cuando puedas entra al Discord y háblame para que te identifique y te asigne el canal para el proyecto. :)

**Comment by davidam** [comment]
Hola,

Os adjunto un logo que pone Damegender es el que tengo en Twitter. Si
por temas de diseño no se puede usar, podéis elegir el de la serpiente
que está deprecated.

Me parece bien asignar una sesión de trabajo proponme día y horas y
qué debería hacer (video-charla, atender el chat, etc.)

Esta tarde miro lo del discord.

Saludos.

El 20/9/21, Israel Saeta Pérez ***@***.***> escribió:
> Hola. Mirando las issues, las veo un poco abstractas y sin más definición
> puede que le cueste a la gente ponerse a hacerlas. Así que yo te recomiendo
> que o bien las expliques un poco más directamente en la issue (preferible),
> o bien agendes alguna sesión de trabajo en la que puedas explicar cómo va el
> tema a la gente interesada.

>

> Respecto al logo, es por no romper el diseño de
> https://hacktoberfestes.dev/, ya que todos los proyectos tienen logo y si no
> quedaría algo raro uno sin logo. Si no se te ocurre ninguno nos inventamos
> nosotros uno que pegue.

>

> Cuando puedas entra al Discord y háblame para que te identifique y te asigne
> el canal para el proyecto. :)

>

> --

> You are receiving this because you were mentioned.

> Reply to this email directly or view it on GitHub:

> https://github.com/HacktoberfestES/hacktoberfestES2021-web/issues/16#issuecomment-922668608


-- 
David Arroyo Menéndez
http://www.davidam.com

**Comment by carmeco** [comment]
Hola @davidam !

Estoy añadiendo el proyecto a la web. El logo entiendo que es este no?
![damegender](https://user-images.githubusercontent.com/83513098/134344972-9988e128-b38d-46cc-afa5-9723db33674f.png)

Por otro lado, en el apartado 'Comunidad' pongo algo o lo quitamos?

**Comment by davidam** [comment]
Sí, es ese.

En el apartado comunidad no sé que decir. Intenté crear una lista, un
telegram y tal y no se metía un número algo decente de personas como
para que mereciera la pena hacer eso en vez de enviar correos
personales o cosas así. Generalmente, aprovecho las charlas que doy
para generar las simpatías y supongo que el equipo de URJC me ayuda a
la diseminación.

Saludos.

2021-09-22 14:40 GMT+02:00, carmeco ***@***.***>:
> Hola @davidam !

>

> Estoy añadiendo el proyecto a la web. El logo entiendo que es este no?

> ![damegender](https://user-images.githubusercontent.com/83513098/134344972-9988e128-b38d-46cc-afa5-9723db33674f.png)

>

> Por otro lado, en el apartado 'Comunidad' pongo algo o lo quitamos?

>

> --

> You are receiving this because you were mentioned.

> Reply to this email directly or view it on GitHub:

> https://github.com/HacktoberfestES/hacktoberfestES2021-web/issues/16#issuecomment-924891660


-- 
David Arroyo Menéndez
http://www.davidam.com

**Comment by davidam** [comment]
Hola,

Os paso mi usuario de Discord davidam#4593

Saludos!

El 22/9/21, David Arroyo Menéndez ***@***.***> escribió:
> Sí, es ese.
>
> En el apartado comunidad no sé que decir. Intenté crear una lista, un
> telegram y tal y no se metía un número algo decente de personas como
> para que mereciera la pena hacer eso en vez de enviar correos
> personales o cosas así. Generalmente, aprovecho las charlas que doy
> para generar las simpatías y supongo que el equipo de URJC me ayuda a
> la diseminación.
>
> Saludos.
>
> 2021-09-22 14:40 GMT+02:00, carmeco ***@***.***>:
>> Hola @davidam !
>
>>
>
>> Estoy añadiendo el proyecto a la web. El logo entiendo que es este no?
>
>> ![damegender](https://user-images.githubusercontent.com/83513098/134344972-9988e128-b38d-46cc-afa5-9723db33674f.png)
>
>>
>
>> Por otro lado, en el apartado 'Comunidad' pongo algo o lo quitamos?
>
>>
>
>> --
>
>> You are receiving this because you were mentioned.
>
>> Reply to this email directly or view it on GitHub:
>
>> https://github.com/HacktoberfestES/hacktoberfestES2021-web/issues/16#issuecomment-924891660
>
>
> --
> David Arroyo Menéndez
> http://www.davidam.com
>


-- 
David Arroyo Menéndez
http://www.davidam.com

**Comment by carmeco** [comment]
Vale, ningún problema, lo ponemos sin comunidad. Ya lo tienes en la web!

**Comment by dukebody** [comment]
@davidam ¿Puedes entrar al servidor https://discord.gg/pgtkJcqVN4? Avísanos cuando estés dentro y te otorgamos el rol adecuado.
