### ISSUE TITLE
[ACTIVIDAD] Cómo ganar dinero siendo estudiante gracias a Google Summer of Code

### ISSUE THREAD

**Issue by astrojuanlu** [HacktoberfestES/hacktoberfestES2021-web#17]
### Nombre

Cómo ganar dinero siendo estudiante gracias a Google Summer of Code

### Fecha y hora

2021-09-21T12:00Z

### Enlace

https://www.eventbrite.es/e/registro-como-ganar-dinero-siendo-estudiante-gracias-a-google-summer-of-code-170120830985?aff=hacktoberfestes

### Descripción corta

Google Summer of Code es un programa de Google que financia a estudiantes para que trabajen en proyectos de software libre y código abierto. Hablaremos de organizaciones y proyectos relacionados con la ciencia y la ingeniería, ¡si bien el evento es abierto para cualquier persona!

### Descripción larga

¿Eres estudiante universitario? ¿Quieres trabajar en proyectos de software abierto ganando dinero desde tu casa?

En esta charla hablaremos sobre Google Summer of Code, un programa de Google que financia a estudiantes para que trabajen en proyectos de software libre y código abierto. Pondremos especial atención a organizaciones y proyectos relacionados con la ciencia y la ingeniería, ¡si bien el evento es abierto para cualquier persona!

La charla se retransmitirá en abierto gratuitamente en YouTube y Twitch.tv.

Más información en https://astrojuanlu.github.io/charla-gsoc/

**Comment by carmeco** [comment]
Hola @astrojuanlu!

Acabo de añadir la charla en la Agenda. Si quieres cambiar algo dime.

**Comment by astrojuanlu** [comment]
Gracias @carmeco ! 🙌🏽
