### ISSUE TITLE
[PROYECTO] GeoSearch - JavaScript

### ISSUE THREAD

**Issue by hhkaos** [HacktoberfestES/hacktoberfestES2021-web#18]
### Nombre

GeoSearch

### Enlace a Github

https://github.com/GeoVoluntarios/geovoluntarios-buscador-web-geolocalizadas

### Logo

![GeoSearch logo](https://user-images.githubusercontent.com/826965/134635737-e8a1a4bc-1537-4306-9fdd-68621923d8dc.png)

### Tecnologías empleadas

* HTML
* CSS
* ES6
* [ArcGIS API for JavaScript](https://developers.arcgis.com/javascript/latest/)

### Descripción corta

It is a client-side application that allows anyone to provide a search experience of geolocated elements. It could be physical elements, websites focus on a specific area, etc.

### Prepara tu proyecto para el HacktoberfestES

- [X] El proyecto está marcado con la etiqueta `hacktoberfest`.
- [X] El proyecto tiene un README indicando cómo configurarlo para desarrollar en él.
- [X] El proyecto tiene creadas issues con información clara sobre las mejoras a implementar.

### Comentarios adicionales

Cualquier duda pueden contactar a través de los issues o conmigo (@hhkaos #9715) en Discord 😄

**Comment by carmeco** [comment]
Hola @hhkaos ! Ya lo tienes en la web :)

**Comment by hhkaos** [comment]
Gracias!!
