### ISSUE TITLE
[PROYECTO] <Helpbuttons.org> - <React/Next-Node-PostGis>

### ISSUE THREAD

**Issue by watchoutfreedom** [HacktoberfestES/hacktoberfestES2021-web#19]
### Nombre

Helpbuttons.org

### Enlace a Github

https://github.com/helpbuttons

### Logo

![apple-touch-icon](https://user-images.githubusercontent.com/23015314/134641391-dfcf1f30-b7bb-4c41-bfe7-b9ee94529450.png)

### Tecnologías empleadas

React, NextJS, NodeJS, PostGIS, LoopBack

### Descripción corta

Custom Coollab Network Platform. The goal is to have a tool that allows everyone to make their own collaborative tool (like Glovo, blablaCar, Airbnb or so many other fields of collaboration), with the minimum resources. We made a prototype that we're building again with new technologies after a learning process. We made a modular design that can be adapt to all those uses and we need the community to extend those modules to make a bigger, federated network of collab networks. 

### Prepara tu proyecto para el HacktoberfestES

- [X] El proyecto está marcado con la etiqueta `hacktoberfest`.
- [X] El proyecto tiene un README indicando cómo configurarlo para desarrollar en él.
- [X] El proyecto tiene creadas issues con información clara sobre las mejoras a implementar.

### Comentarios adicionales

Ask any question you have!
![HB_QUE_OFRECE](https://user-images.githubusercontent.com/23015314/134641544-3ca6e5b2-58f5-41f3-8d20-3389d5ccfb51.jpg)

**Comment by carmeco** [comment]
Hola @watchoutfreedom ! Ya tenéis el proyecto en la web :)

**Comment by watchoutfreedom** [comment]
> Hola @watchoutfreedom ! Ya tenéis el proyecto en la web :)

Hola @carmeco  gracias! Podríamos cambiar la descripción por esta ? 👍 

Custom Collaboration Platform. The goal s to allows everyone to make their own collaborative tool (like Glovo, blablaCar, Airbnb or any other fields of collaboration). We made a prototype that we're rebuilding with new technologies after a learning process. We need special help with React , NextJS and API communication, and Leaflet integration. 

gracias

**Comment by dukebody** [comment]
@watchoutfreedom ¡actualizada!
