### ISSUE TITLE
[PROYECTO] Recursos de Programación - Markdown

### ISSUE THREAD

**Issue by cesaralvrz** [HacktoberfestES/hacktoberfestES2021-web#20]
### Nombre

Recursos de Programación

### Enlace a Github

https://github.com/Acadeller/recursos-programacion

### Logo

![acadeller](https://user-images.githubusercontent.com/57325703/135318761-caa48566-ab88-4736-b032-addf98a445b4.png)

### Tecnologías empleadas

Markdown para escribir el README.

Lenguajes para agregar recursos:
- C
- CSS
- Dart
- Go
- HTML
- Java
- JavaScript
- Kotlin
- PHP
- Python
- R
- Ruby
- Rust
- Scala
- SQL
- Swift

### Descripción corta

El objetivo principal de este repositorio, es recopilar la mayor cantidad posible de recursos de programación que existan en internet, para que estén al alcance de cualquier persona en todo momento. El repositorio está dividido por lenguajes de programación, en cada lenguaje podrás encontrar recursos para dicho lenguaje, frameworks, librerías y mucho más.

### Prepara tu proyecto para el HacktoberfestES

- [X] El proyecto está marcado con la etiqueta `hacktoberfest`.
- [X] El proyecto tiene un README indicando cómo configurarlo para desarrollar en él.
- [x] El proyecto tiene creadas issues con información clara sobre las mejoras a implementar.

**Comment by carmeco** [comment]
Hola @cesaralvrz ! Ya tienes el proyecto en la web.

**Comment by cesaralvrz** [comment]
Está todo perfecto 🚀

**Comment by dukebody** [comment]
@cesaralvrz nos puedes decir tu usuario en el servidor de Discord? Para darte el rol correspondiente y enseñarte el canal.

**Comment by cesaralvrz** [comment]
Me acabo de unir, es @acadeller mi usuario
