### ISSUE TITLE
[PROYECTO] dog - C

### ISSUE THREAD

**Issue by JuanjoSalvador** [HacktoberfestES/hacktoberfestES2021-web#21]
### Nombre

Dog

### Enlace a Github

https://github.com/JuanjoSalvador/dog

### Tecnologías empleadas

C, Makefile

### Descripción corta

> La existencia de un comando `cat` implica la existencia de un comando `dog`.

Bajo esa premisa, decidí montar este paquete que te permite disponer de tu propio perrete en la terminal. Es un proyecto muy básico y que nace como una broma entre programadores, pero útil para introducirse en la programación y especialmente en las contribuciones de código abierto.

### Prepara tu proyecto para el HacktoberfestES

- [X] El proyecto está marcado con la etiqueta `hacktoberfest`.
- [X] El proyecto tiene un README indicando cómo configurarlo para desarrollar en él.
- [X] El proyecto tiene creadas issues con información clara sobre las mejoras a implementar.

**Comment by carmeco** [comment]
Hola @JuanjoSalvador!

Tienes algun logo para ponerlo en la web?

**Comment by JuanjoSalvador** [comment]
Oficialmente no, pero podemos utilizar este sacado de Flaticon.

![perro](https://user-images.githubusercontent.com/5058655/135709095-f4ff0a62-bbcb-4170-8039-959fa3cffe3e.png)

Atribución: 

```
<div>Iconos diseñados por <a href="https://www.flaticon.es/autores/flat-icons" title="Flat Icons">Flat Icons</a> from <a href="https://www.flaticon.es/" title="Flaticon">www.flaticon.es</a></div>
```

**Comment by carmeco** [comment]
Ya lo tienes en la web! Si quieres cambiar alguna cosa dime :)

**Comment by JuanjoSalvador** [comment]
Genial, muchas gracias!

**Comment by dukebody** [comment]
@JuanjoSalvador nos dices tu usuario de Discord? Ya hemos creado los canales de tu proyecto. :)

**Comment by JuanjoSalvador** [comment]
@dukebody `Ironforge#3569`

¡gracias!
