### ISSUE TITLE
[PROYECTO] Acelerador de proyectos Django

### ISSUE THREAD

**Issue by adriancast** [HacktoberfestES/hacktoberfestES2021-web#5]
### Nombre

django-template

### Logo
![django-template-logo](https://user-images.githubusercontent.com/17761956/132141507-5c4237d7-388c-4ffb-ad01-47bfe2be2989.png)

### Enlace

https://github.com/adriancast/django-template

### Descripción corta
Cookiecutter para crear aplicaciones "production ready" en menos de 5 minutos utilizando Docker y Django. Rellena un simple formulario y podrás crear tu próxima startapp.

**Tecnologias:**  Docker, Django, Grafana, Let's Encrypt + certbot  y muchas más con tu ayuda ;)

### Descripción larga

En los últimos meses me he propuesto crear una plantilla capaz de crear aplicaciones Django production ready utilizando herramientas automatizadas. Actualmente, la template es capaz de generar proyectos añadiendo:

1. Estructura básica proyecto Django
2. Docker para gestionar el tema de instalación en el servidor
3. Gestión de ficheros estáticos utilizando NGINX
4. Automatización de la renovación de certificados HTTPS utilizando Let's encrypt y Cerbot (uno no sabe el rollo que es gestionar esto hasta que le toca hacerlo a manija varias veces)

También se añaden addons molones que facilitan la vida del desarrollador. Por ahora la plantilla soporta:

1. Integración con Grafana + Prometheus. Se exponen métricas básicas de una aplicación de Django y se crean visualizaciones de forma predeterminada.
2. Monitorización de errores en tiempo de ejecución utilizando Sentry.

Ahora viene la parte de que podemos hacer con este proyecto. Actualmente la principal carencia es la falta de documentación. Hay algunas partes de la template que tendriamos que detallar mas extensamente con el objetivo de que la persona que utilice la template sea capaz de entender que está haciendo. Lo mas guay de trabajar en un proyecto de estos es que te empapas de como funcionan las cosas por debajo. Creo que la gente que le mole cacharrear y ver como funcionan las cosas por debajo puede disfrutar mucho añadiendo features a esta template.

A parte de documentación, hay mil cosas por añadir. Una de las tantas cosas que le faltan es configurar las caches de Django (Django settings + Docker support)

En el caso de que alguien se anime a hacer una app entera de Django para la Hackaton, también me gustaría proponer que se diera una oportunidad a esta template con el objetivo de poder recibir feedback de usuarios.

Muchas gracias por todo,
estamos en contacto!

**Comment by dukebody** [comment]
¡Hola @adriancast ! Mola mucho lo que describes. ¡Gracias por tu propuesta!

Creo que lo mejor sería proponer esto principalmente como proyecto. Es posible que se creen nuevas apps enteras para el Hacktoberfest, pero no creo que sea algo muy probable o común. En cualquier caso si pasase obviamente podemos sugerir usar esta plantilla.

Si lo proponemos como proyecto necesitaríamos sobre el proyecto, aparte de lo que ya nos has pasado:
- Logo. Te puedes inventar alguna fusión entre los logos de las tecnologías que se usan, por ejemplo. Si no sacas nada, ya nos inventamos algo nosotr@s.
- Descripción corta de máximo 280 caracteres, para la web.
- Confirmar que las tecnologías principales empleadas son: CookieCutter, Django, Docker, NGINX, Grafana+Prometheus.

Con esto ya lo podemos poner en la web.

Luego en el repo de Github del proyecto, antes de que llegue octubre:
1. Ponerle la etiqueta `hacktoberfest`.
2. Revisar que está claro cómo configurar el proyecto para desarrollarlo en su README.
3. Crear issues con información clara sobre las mejoras a implementar.

¿Cómo lo ves?

**Comment by adriancast** [comment]
Buenas @dukebody 

Me parece genial lo que comentas en el último comentario 👍🏼 

Te he actualizado la descripción y el logo en la issue. Te confirmo que las tecnologias principales que se utilizan son las que comentas aunque espero que al final de la hackaton sean muchas más 😄. Comentar que tambien se utiliza Certbot y Let's Encrypt para el tema de los certificados HTTPS.

Respecto a lo de la etiqueta hacktoberfest, podrias confirmarme si tengo que meterla en el about del repositorio ?
![image](https://user-images.githubusercontent.com/17761956/132141565-7a1da36e-6c62-4ef2-ad44-795ee0550594.png)
Voy un poco perdido 😵‍💫 .

Si veis que el logo es muy grande o cualquier cosa avisadme y lo reestructuro.

Un saludo

**Comment by carmeco** [comment]
Hola @adriancast !

Acabo de añadir tu Proyecto a la web, pero me falta el apartado de 'Comunidad'. ¿Qué ponemos Python Mallorca, Python España o lo dejamos en blanco?

@dukebody Habría que añadir el apartado Comunidad al issue.

Por cierto, me parece muy guay el proyecto! :)

**Comment by adriancast** [comment]
Buenas @carmeco ,

puedes vincularlo a Python Mallorca 😄 👍🏼 

Esperemos que el proyecto llegue a buen puerto y pueda facilitar la vida a un par de devs 😉 .

Un saludo!

**Comment by carmeco** [comment]
Ok!
