### ISSUE TITLE
[TALLER] Crea tu juego de peleas usando un CLI

### ISSUE THREAD

**Issue by adriancast** [HacktoberfestES/hacktoberfestES2021-web#6]
### Nombre

street-fighter-cli

### Logo

![image](https://user-images.githubusercontent.com/17761956/132141766-8f113e9e-be9d-4c58-9ba7-9efea4004379.png)

### Descripción corta

Crea tu própio juego juego de peleas por turnos 👊🏼 . En este taller aprenderas los fundamentos para crear un juego en el que varios personajes se atacan entre ellos. Además, repasarás conceptos básicos de programación como la programación orientada a objetos entre muchos otros.

### Descripción Larga

Me gustaría proponer un taller donde los participantes crearan un juego de peleas a base de turnos utilizando la CLI. El taller estaría orientado para gente que está empezando a programar. Por ejemplo, gente que está empezando un FP o empezando la universidad.

Haciendo el juego se podrían explicar las siguientes ideas:

1. Introducción a Python. Tipos de variables y sintaxis básica.
2. Iteración de listas.
3. Programación orientada a objetos: Creación de personajes con estadísticas.
4. Uso de funciones: simulación de un turno de un combate.

Creo que es una actividad que deja mucha rienda suelta a los participantes, una vez entienden los fundamentos para poder resolver el ejercicio, muchas veces se animan a añadir funcionalidades nuevas o a personalizar los turnos de combate.

**Comment by dukebody** [comment]
¡Hola @adriancast ! Gracias por tu propuesta, mola un montón.

Algunos comentarios:
1. ¿Lo orientarías a gente que no sabe programar y empezar desde cero? Creo que hasta llegar a programación orientada a objetos se tarda un rato. Si se quiere empezar de 0 seguramente habría que hacer varias sesiones. Yo creo que es mejor enfocarlo a gente que ya sabe programar un poco, porque si no puede hacerse demasiado largo.
2. ¿Qué fechas orientativas pondrías? Estamos intentando hacer las actividades preferentemente en fin de semana por la tarde, para que pueda sumarse gente de LATAM. ¿Qué finde te va bien? ¿O prefieres otro día?
3. Una vez pensado y decidido esto, ¿podrías pasarnos una descripción corta de máx 280 caracteres del evento? Luego como descripción larga podemos adaptar lo que ya has escrito.

¡Vamos hablando!

**Comment by adriancast** [comment]
Buenas @dukebody ,

Si te parece bien te voy contestando punto a punto:

1. Como comentas, lo ideal seria que sean personas que tengan conocimientos básicos de programación. Creo que el ejemplo perfecto es una persona que esté al principio del FP o un estudiante de ingeniería que lleve 1 añito en la carrera. Una persona que no tiene conocimientos previos se le puede hacer un poco cuesta arriba. Aunque nada es imposible 😉 
2. Vienes por la tarde y fin de semana me va perfecto aunque estoy pendiente de confirmar cronograma. Sigo estudiando en la universidad y me gustaria asegurar que no se solape el taller con ninguna entrega de la universidad. Tan pronto como tenga el crono de la uni y pueda hablar con los profesores os confirmo 👍🏼 
3. Marchando!

**Comment by carmeco** [comment]
Hola @adriancast ! 

¿Tenemos fecha y hora para el taller?

**Comment by adriancast** [comment]
Buenas, 

lo estoy comentado con @dukebody por telegram, pero creo que el sábado 16 a las 17:00 seria buena hora.

Tengo una horilla muerta ahora mismo, voy a darle caña al repo de ejemplo.

Un saludo

**Comment by carmeco** [comment]
Perfecto! :)
