### ISSUE TITLE
[PROYECTO] RSSPAPER - Clojure y HTML

### ISSUE THREAD

**Issue by tanrax** [HacktoberfestES/hacktoberfestES2021-web#8]
### Nombre

RSSPAPER

### Enlace a Github

https://github.com/tanrax/RSSPAPER

### Logo

![imagen](https://user-images.githubusercontent.com/4553672/132129699-f7fc8186-4281-46e3-8bee-d0caee2175f4.png)

### Tecnologías empleadas

Clojure y un motor de plantillas HTML clon de Django.

### Descripción corta

Genera una página estática con las últimas noticias de tus feeds favoritos. Crea un HTML/PWA que puedes leer o instalar en tu tableta o móvil.

### Prepara tu proyecto para el HacktoberfestES

- [X] El proyecto está marcado con la etiqueta `hacktoberfest`.
- [X] El proyecto tiene un README indicando cómo configurarlo para desarrollar en él.
- [X] El proyecto tiene creadas issues con información clara sobre las mejoras a implementar.

**Comment by carmeco** [comment]
Hola @tanrax ! Yaestá puesto en la web :)

**Comment by tanrax** [comment]
Gracias!
